CREATE DATABASE IF NOT EXISTS DATA226;
CREATE SCHEMA IF NOT EXISTS DATA226.MARKET;

CREATE TABLE IF NOT EXISTS DATA226.MARKET.STOCKS_OHLCV (
  SYMBOL STRING NOT NULL,
  DT DATE NOT NULL,
  OPEN NUMBER(18,6),
  HIGH NUMBER(18,6),
  LOW  NUMBER(18,6),
  CLOSE NUMBER(18,6),
  VOLUME NUMBER(38,0),
  CONSTRAINT PK_STOCKS PRIMARY KEY (SYMBOL, DT)
);

CREATE OR REPLACE VIEW DATA226.MARKET.VW_LAST_180 AS
SELECT SYMBOL, DT, CLOSE AS ACTUAL_PRICE
FROM DATA226.MARKET.STOCKS_OHLCV
WHERE DT >= DATEADD('day', -180, CURRENT_DATE());

CREATE TABLE IF NOT EXISTS DATA226.MARKET.STOCKS_FORECAST (
  SYMBOL STRING,
  DT DATE,
  PREDICTED_PRICE FLOAT,
  PREDICTED_LOWER_BOUND FLOAT,
  PREDICTED_UPPER_BOUND FLOAT
);

CREATE TABLE IF NOT EXISTS DATA226.MARKET.STOCKS_FINAL AS
SELECT
  SYMBOL, DT, OPEN, HIGH, LOW, CLOSE AS PRICE,
  NULL::FLOAT AS PREDICTED_LOWER_BOUND,
  NULL::FLOAT AS PREDICTED_UPPER_BOUND,
  FALSE AS IS_FORECAST
FROM DATA226.MARKET.STOCKS_OHLCV
UNION ALL
SELECT
  SYMBOL, DT, NULL, NULL, NULL, PREDICTED_PRICE,
  PREDICTED_LOWER_BOUND, PREDICTED_UPPER_BOUND,
  TRUE
FROM DATA226.MARKET.STOCKS_FORECAST;
